#@author 王宇帆 183509578@qq.com

#表结构

DROP DATABASE IF EXISTS `puxi`;
CREATE DATABASE IF NOT EXISTS `puxi` CHARSET=UTF8;
use company;
CREATE TABLE IF NOT EXISTS `puxi_unit`(
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "单位id",
`name` VARCHAR(255) NOT NULL UNIQUE KEY COMMENT "单位名",
`address` VARCHAR(255) NOT NULL DEFAULT "" COMMENT "单位地址",
`email` VARCHAR(100) NOT NULL DEFAULT "" COMMENT "联系邮箱",
`phone` VARCHAR(16) COMMENT "手机号",
`telephone` VARCHAR(16) COMMENT "座机号",
`description` VARCHAR(500) NOT NULL DEFAULT "" COMMENT "单位描述"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="单位表";


CREATE TABLE IF NOT EXISTS `puxi_database_level`(
`id` TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "级别编号",
`name` VARCHAR(20) NOT NULL UNIQUE KEY COMMENT "级别名"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="数据库级别表";

INSERT INTO `puxi_database_level`(name) values ('北大核心期刊'),('中国科技核心期刊'),('CSSCI索引'),('CSCD索引');

CREATE TABLE IF NOT EXISTS `puxi_periodical_category`(
`id` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "id编号",
`name` VARCHAR(50) NOT NULL UNIQUE KEY COMMENT "期刊分类名",
`description` VARCHAR(500) NOT NULL DEFAULT "" COMMENT "期刊分类描述",
`is_nav` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT "是否在菜单上显示:1否2是",
`status` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT "是否上线：1否2是",
`sortcode` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT "排序码",
`pid` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "期刊分类父id",
`typestr` VARCHAR(50) NOT NULL DEFAULT "" COMMENT "期刊分类层次字符",
`level` TINYINT NOT NULL DEFAULT 1 COMMENT "期刊分类层级"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="期刊分类表";

CREATE TABLE IF NOT EXISTS `puxi_periodical`(
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "编号",
`title` VARCHAR(50) NOT NULL UNIQUE KEY COMMENT "期刊标题名",
`first_letter` CHAR(1) NOT NULL DEFAULT "" COMMENT "期刊名首字母",
`description` VARCHAR(500) NOT NULL DEFAULT "" COMMENT "期刊描述",
`image` VARCHAR(255) NOT NULL DEFAULT "" COMMENT "期刊封面",
`foreign_title` VARCHAR(255) NOT NULL DEFAULT "" COMMENT "期刊外文名",
`issn` CHAR(9) UNIQUE KEY COMMENT "国际标准刊号",
`cn` VARCHAR(10) UNIQUE KEY COMMENT "国内统一刊号",
`viewed` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "浏览量",
`download` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "下载量",
`lang` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT "语种1代表中文,2代表英文",
`created_at` DATETIME NOT NULL COMMENT "期刊数据添加时间",
`updated_at` DATETIME NOT NULL COMMENT "期刊数据更新时间",
`establish_at` DATETIME COMMENT "创刊时间",
`cycle` TINYINT UNSIGNED NOT NULL COMMENT "出版周期：1代表旬刊,2半月刊,3月刊,4双月刊,5季刊,6半年刊,7年刊",
`status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "期刊状态1代表不上线,2代表上线",
`is_rm` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "用于期刊的软删除1保留，2删除",
`mobile` VARCHAR(15) NOT NULL DEFAULT "" COMMENT "手机号",
`email` VARCHAR(100) NOT NULL DEFAULT ""  COMMENT "期刊邮箱号",
`postal_code` VARCHAR(10) NOT NULL DEFAULT "" COMMENT "邮发代号",
`price_info` VARCHAR(20) NOT NULL DEFAULT "" COMMENT "定价信息",
`typestr` VARCHAR(50) NOT NULL DEFAULT "" COMMENT "期刊分类",
`level_ids` VARCHAR(20) NOT NULL DEFAULT "" COMMENT "期刊级别",
`competent_unit` VARCHAR(100)  NOT NULL DEFAULT "" COMMENT "期刊主管单位",
`sponsor_unit` VARCHAR(100)  NOT NULL DEFAULT "" COMMENT "期刊主办单位",
`editorial_unit` VARCHAR(100) NOT NULL DEFAULT "" COMMENT "期刊编辑单位"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="期刊表";

CREATE TABLE IF NOT EXISTS `puxi_author`(
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "作者id",
`name` VARCHAR(20) NOT NULL COMMENT "作者姓名",
`address` VARCHAR(255) NOT NULL COMMENT "作者地址"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="作者分类表";

CREATE TABLE IF NOT EXISTS `puxi_paper`(
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "id编号",
`title` VARCHAR(50) NOT NULL COMMENT "标题",
`abstract` VARCHAR(500) NOT NULL COMMENT "摘要",
`keywords` VARCHAR(255) NOT NULL COMMENT "关键词",
`doi` VARCHAR(255) COMMENT "数字对象唯一标识符",
`periodical_id` INT UNSIGNED NOT NULL COMMENT "来源期刊",
`filename` CHAR(32) COMMENT "文件名",
`status` TINYINT UNSIGNED DEFAULT 0 COMMENT "是否上线0不上线,1上线"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="论文表";

CREATE TABLE IF NOT EXISTS `puxi_paper_author`(
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "id编号",
`pid` INT UNSIGNED NOT NULL COMMENT "关联的论文id",
`aid` INT UNSIGNED NOT NULL COMMENT "关联的作者id"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="论文作者表";

CREATE TABLE IF NOT EXISTS `puxi_member`(
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "用户id",
`username` VARCHAR(20) UNIQUE KEY NOT NULL COMMENT "用户昵称",
`password` VARCHAR(255) NOT NULL COMMENT "密码",
`phone` VARCHAR(11) UNIQUE KEY NOT NULL COMMENT "手机号",
`gender` ENUM('1','2','3') NOT NULL DEFAULT '3' COMMENT "性别:1男2女3保密",
`avatar` VARCHAR(255) NOT NULL DEFAULT "" COMMENT "头像图片路径",
`created_at` DATETIME NOT NULL COMMENT "创建时间",
`updated_at` DATETIME NOT NULL COMMENT "更新时间",
`remember_token` VARCHAR(100) COMMENT "记住密码token",
`status` ENUM('1','2')  NOT NULL DEFAULT '2' COMMENT "1不启用,2启用默认"
)ENGINE=InnoDB CHARSET DEFAULT CHARSET=utf8 COMMENT="用户表";

CREATE TABLE IF NOT EXISTS `puxi_role` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT "角色编号",
  `role_name` VARCHAR(20) NOT NULL UNIQUE KEY COMMENT "角色名",
  `auth_ids` text COMMENT "角色权限集合",
  `auth_ac` text COMMENT "角色权限控制器方法集合"
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="角色表";

CREATE TABLE IF NOT EXISTS `puxi_manager`(
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "管理员编号",
`username` VARCHAR(20) UNIQUE KEY NOT NULL COMMENT "管理员昵称",
`password` VARCHAR(255) NOT NULL COMMENT "登录密码",
`gender` ENUM('1','2','3') NOT NULL DEFAULT '3' COMMENT "性别:1男2女3保密",
`created_at` DATETIME  NOT NULL COMMENT "用户创建时间",
`updated_at` DATETIME NOT NULL COMMENT "用户信息更新时间",
`mobile` VARCHAR(11) NOT NULL DEFAULT "" COMMENT "手机号",
`email` VARCHAR(100) UNIQUE KEY NOT NULL DEFAULT ""  COMMENT "邮箱地址",
`remember_token` varchar(100) COMMENT "记住密码token",
`status` ENUM('1','2')  NOT NULL DEFAULT '2' COMMENT "1不启用,2启用",
`role_id` TINYINT UNSIGNED NOT NULL COMMENT "关联角色id"
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="后台管理员表";

CREATE TABLE IF NOT EXISTS `puxi_auth` (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "权限编号",
  `auth_name` varchar(20) NOT NULL COMMENT "权限名",
  `controller` varchar(40)  DEFAULT "" COMMENT "控制器名",
  `action` varchar(30)  DEFAULT "" COMMENT "方法名",
  `pid` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "权限父级id",
  `is_nav` ENUM('1','2')  NOT NULL DEFAULT '1' COMMENT "是否作为导航显示1是2否",
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="权限表";

#索引